<a href="https://colab.research.google.com/github/fredyah/tudui-pytorch/blob/main/tudui_pytorch_WhatIs_nn_MaxPool2d.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import torch
import torchvision
from torch import nn
from torch.nn import Conv2d, Sigmoid, MaxPool2d
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

In [22]:
class Tudui(nn.Module):
  def __init__(self):
    super(Tudui, self).__init__()
    self.maxpool1 = MaxPool2d(kernel_size=3, ceil_mode=True)

  def forward(self, input):
    output = self.maxpool1(input)
    return output

In [23]:
class TuduiA(nn.Module):
  def __init__(self):
    super(TuduiA, self).__init__()
    self.maxpool1 = MaxPool2d(kernel_size=3, ceil_mode=False)

  def forward(self, input):
    output = self.maxpool1(input)
    return output

In [24]:
input = torch.tensor([[1, 2, 0, 3, 1],
            [0, 1, 2, 3, 1],
            [1, 2, 1, 0, 0],
            [5, 2, 3, 1, 1],
            [2, 1, 0, 1, 1]], dtype=torch.float32)

input = torch.reshape(input, (-1, 1, 5, 5))  ## -1 是用於自動判斷，如果不知道該用什麼，就可以輸入 -1
print(input)
print(input.shape)

tensor([[[[1., 2., 0., 3., 1.],
          [0., 1., 2., 3., 1.],
          [1., 2., 1., 0., 0.],
          [5., 2., 3., 1., 1.],
          [2., 1., 0., 1., 1.]]]])
torch.Size([1, 1, 5, 5])


In [26]:
tudui = Tudui()
output = tudui(input)
print("Ceil-Mode = True")
print(output)
print()
tuduiA = TuduiA()
outputA = tuduiA(input)
print("Ceil-Mode = False")
print(outputA)


Ceil-Mode = True
tensor([[[[2., 3.],
          [5., 1.]]]])

Ceil-Mode = False
tensor([[[[2.]]]])
